baseurl = "/"
Paginate = 5

[params]
  env = "development"

[[menu.main]]
  name = "Home"
  weight = 1
  identifier = "home"
  url = "/"

# datocms:start
title = "Shine My Crown"
languageCode = "en"
# datocms:end
